### ISSUE TITLE
Error when run "base run_single.sh" at step 6 Test the installation

### ISSUE THREAD

**Issue by chris-opendata** [snap-stanford/GraphGym#20]
I have so far tried it with torch1.4.0, 1.5.0 and lately 1.7.0 on my ubuntu18.04. I successfully installed them, but faced errors when I ran the step 6 Test the installation. The 1.7.0 is a step closer but it still had the following error when 'bash run_single.sh'. I searched and found nowhere to see  libcusparse.so.
```
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from graphgym.loader import create_dataset, create_loader
  File "/home/hdd2nd/dev/projects/gnn/GraphGym/graphgym/loader.py", line 6, in <module>
    from deepsnap.dataset import GraphDataset
  File "/home/hdd2nd/dev/projects/gnn/DeepSNAP/deepsnap/__init__.py", line 5, in <module>
    import deepsnap.graph
  File "/home/hdd2nd/dev/projects/gnn/DeepSNAP/deepsnap/graph.py", line 9, in <module>
    from torch_geometric.utils import to_undirected
  File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/site-packages/torch_sparse/__init__.py", line 15, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
  File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcusparse.so.10: cannot open shared object file: No such file or directory
```

I also listed the installation steps as follows for reference. I successfully installed all by following closely the instructions on https://github.com/snap-stanford/GraphGym. Note that I installed torch-geometric following https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html because the commands from GraphGym didn't work.

```
>conda create -n graphgym python=3.7
>conda activate graphgym
>pip install torch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0
>(graphgym) $ pip install torch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0
>(graphgym) $ pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
>(graphgym) $ pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
>(graphgym) $ pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
>(graphgym) $ pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
>(graphgym) $ pip install torch-geometric
>(graphgym) $ git clone https://github.com/snap-stanford/DeepSNAP
>(graphgym) $ cd DeepSNAP
>(graphgym) $ pip install -e .
>(graphgym) $ cd ..
>(graphgym) $ git clone https://github.com/snap-stanford/GraphGym
>(graphgym) $ cd GraphGym/
>(graphgym) $ pip install -r requirements.txt
>(graphgym) $ pip install -e .
```

Thank you

**Comment by whtitefall** [comment]
I have the same issue with PyTorch1.4 and PyG installation, 

I installed PyTorch 1.7+cpu, when I run the .sh file I have following error

```

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from graphgym.loader import create_dataset, create_loader
  File "/data/huyuanzheng/GraphGym/graphgym/loader.py", line 6, in <module>
    from deepsnap.dataset import GraphDataset
  File "/data/huyuanzheng/anaconda3/envs/graphgym/lib/python3.7/site-packages/deepsnap/__init__.py", line 5, in <module>
    import deepsnap.graph
  File "/data/huyuanzheng/anaconda3/envs/graphgym/lib/python3.7/site-packages/deepsnap/graph.py", line 9, in <module>
    from torch_geometric.utils import to_undirected
  File "/data/huyuanzheng/anaconda3/envs/graphgym/lib/python3.7/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/data/huyuanzheng/anaconda3/envs/graphgym/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/data/huyuanzheng/anaconda3/envs/graphgym/lib/python3.7/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/data/huyuanzheng/anaconda3/envs/graphgym/lib/python3.7/site-packages/torch_sparse/__init__.py", line 15, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
AttributeError: 'NoneType' object has no attribute 'origin'

```

**Comment by JiaxuanYou** [comment]
Thanks for pointing out the bug! The bug is due to PyTorch Geometric updates the installation script.

I've updated GraphGym to support the latest PyTorch (1.8.0) and the latest PyTorch Geometric. 
I deployed a fresh copy of GraphGym on my side and it works fine.
You may follow the new README to reinstall the environment.

@chris-opendata @whtitefall

**Comment by chris-opendata** [comment]
Thank you Jiaxuan. I will try it out. BTW, will you be able to have a Windows 10 based installation as well?
Best regards
Chris

________________________________

**Comment by chris-opendata** [comment]
Hi JiaxuanYou,

I tried torch1.8.1+cu102 (my cuda version for nvidia driver) today while following the instructions closely. When I preceded to `pip install -r requirements.txt`, it resulted in the following errors after auto Downloading torch-1.8.1-cp37-cp37m-manylinux1_x86_64.whl (804.1 MB)
```
Collecting torch-scatter
  Downloading torch_scatter-2.0.7.tar.gz (21 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/hdd2nd/dev/miniconda3/envs/graphgym/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l79nk47e/torch-scatter_f16bdd4dab584f82896ad52880657ad7/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l79nk47e/torch-scatter_f16bdd4dab584f82896ad52880657ad7/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-d0nd14mr
         cwd: /tmp/pip-install-l79nk47e/torch-scatter_f16bdd4dab584f82896ad52880657ad7/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-l79nk47e/torch-scatter_f16bdd4dab584f82896ad52880657ad7/setup.py", line 8, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/fa/d1/0bade0c3b9222710528de0458ad48407dab46efd7ad3d4fd1be82b68ac2b/torch_scatter-2.0.7.tar.gz#sha256=369184948c838f756eea10464a3fbf8e103e22dc94d7045dbab85b5748bf85f9 (from https://pypi.org/simple/torch-scatter/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached torch_scatter-2.0.6.tar.gz (21 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/hdd2nd/dev/miniconda3/envs/graphgym/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l79nk47e/torch-scatter_15948f5c5b1e4e8d97d597fb879707db/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l79nk47e/torch-scatter_15948f5c5b1e4e8d97d597fb879707db/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-837l6i5b
         cwd: /tmp/pip-install-l79nk47e/torch-scatter_15948f5c5b1e4e8d97d597fb879707db/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-l79nk47e/torch-scatter_15948f5c5b1e4e8d97d597fb879707db/setup.py", line 8, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
WARNING: Discarding 
... ...
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/08/09/07b106f3e74246f4ecf6517013a053b6dd7486c4f889d81f39adc662431f/torch_scatter-1.0.3.tar.gz#sha256=e626993194819ba65cdf89a52fbbb7780569d9e157bc63dbef13ead6b7a33930 (from https://pypi.org/simple/torch-scatter/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading torch_scatter-1.0.2.tar.gz (13 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/hdd2nd/dev/miniconda3/envs/graphgym/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l79nk47e/torch-scatter_036d08b07d4b4e4dab0e3b1d7393e4ca/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l79nk47e/torch-scatter_036d08b07d4b4e4dab0e3b1d7393e4ca/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-6bats41s
         cwd: /tmp/pip-install-l79nk47e/torch-scatter_036d08b07d4b4e4dab0e3b1d7393e4ca/
    Complete output (25 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-l79nk47e/torch-scatter_036d08b07d4b4e4dab0e3b1d7393e4ca/setup.py", line 26, in <module>
        cffi_modules=[osp.join(osp.dirname(__file__), 'build.py:ffi')],
      File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/site-packages/setuptools/dist.py", line 433, in __init__
        k: v for k, v in attrs.items()
      File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/site-packages/setuptools/dist.py", line 708, in finalize_options
        ep(self)
      File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/site-packages/setuptools/dist.py", line 715, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "/tmp/pip-install-l79nk47e/torch-scatter_036d08b07d4b4e4dab0e3b1d7393e4ca/build.py", line 4, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/6a/b0/ecffacddf573c147c70c6e43ce05d24f007155ce3fb436959d3d2a24da46/torch_scatter-1.0.2.tar.gz#sha256=ccda794c25265b3450206b7fb0bf74f16a0b45f3f72d9547a42e44648a32faee (from https://pypi.org/simple/torch-scatter/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading torch_scatter-0.3.0.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/hdd2nd/dev/miniconda3/envs/graphgym/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l79nk47e/torch-scatter_95b898cd279f45d192781e0d3f65a547/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l79nk47e/torch-scatter_95b898cd279f45d192781e0d3f65a547/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-sxj49czy
         cwd: /tmp/pip-install-l79nk47e/torch-scatter_95b898cd279f45d192781e0d3f65a547/
    Complete output (25 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-l79nk47e/torch-scatter_95b898cd279f45d192781e0d3f65a547/setup.py", line 27, in <module>
        cffi_modules=[osp.join(osp.dirname(__file__), 'build.py:ffi')],
      File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/site-packages/setuptools/dist.py", line 433, in __init__
        k: v for k, v in attrs.items()
      File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/site-packages/setuptools/dist.py", line 708, in finalize_options
        ep(self)
      File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/site-packages/setuptools/dist.py", line 715, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/home/hdd2nd/dev/miniconda3/envs/graphgym/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "/tmp/pip-install-l79nk47e/torch-scatter_95b898cd279f45d192781e0d3f65a547/build.py", line 3, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/29/96/566ac314e796d4b07209a3b88cc7a8d2e8582d55819e33f72e6c0e8d8216/torch_scatter-0.3.0.tar.gz#sha256=9e5e5a6efa4ef45f584e8611f83690d799370dd122b862646751ae112b685b50 (from https://pypi.org/simple/torch-scatter/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement torch-scatter (from versions: 0.3.0, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7)
ERROR: No matching distribution found for torch-scatter
```

Meanwhile, I also tried 1.8.0+cu111 by updating cuda to the latest 11.3 aforehand, and then following the instruction successfully. But running 'bash run_single.sh' got the error:
```
OSError: libcudart.so.10.2: cannot open shared object file: No such file or directory
```
It still look for the old version.

I am wondering whether all combinations of torch+cuda listed in your instructional comment are tested. Would you be able to investigate the issue further?

Thank you
Chris
