### ISSUE TITLE
Test the installation

### ISSUE THREAD

**Issue by faker09** [snap-stanford/GraphGym#25]
when i run (bash bash run_single.sh), some error appear, but when i run(bash run_batch.sh), it is ok.   i am not sure if it is a successful installation

**Comment by JiaxuanYou** [comment]
Can you provide more details on what errors did you encounter?

**Comment by faker09** [comment]
Processing...
Traceback (most recent call last):
  File "main.py", line 42, in <module>
    datasets = create_dataset()
  File "/root/GraphGym/graphgym/loader.py", line 197, in create_dataset
    graphs = load_dataset()
  File "/root/GraphGym/graphgym/loader.py", line 111, in load_dataset
    graphs = load_pyg(name, dataset_dir)
  File "/root/GraphGym/graphgym/loader.py", line 33, in load_pyg
    dataset_raw = Planetoid(dataset_dir, name)
  File "/root/anaconda3/envs/graphgym/lib/python3.7/site-packages/torch_geometric/datasets/planetoid.py", line 58, in __init__
    super().__init__(root, transform, pre_transform)
  File "/root/anaconda3/envs/graphgym/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 60, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "/root/anaconda3/envs/graphgym/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 86, in __init__
    self._process()
  File "/root/anaconda3/envs/graphgym/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 165, in _process
    self.process()
  File "/root/anaconda3/envs/graphgym/lib/python3.7/site-packages/torch_geometric/datasets/planetoid.py", line 111, in process
    data = read_planetoid_data(self.raw_dir, self.name)
  File "/root/anaconda3/envs/graphgym/lib/python3.7/site-packages/torch_geometric/io/planetoid.py", line 19, in read_planetoid_data
    items = [read_file(folder, prefix, name) for name in names]
  File "/root/anaconda3/envs/graphgym/lib/python3.7/site-packages/torch_geometric/io/planetoid.py", line 19, in <listcomp>
    items = [read_file(folder, prefix, name) for name in names]
  File "/root/anaconda3/envs/graphgym/lib/python3.7/site-packages/torch_geometric/io/planetoid.py", line 95, in read_file
    out = pickle.load(f, encoding='latin1')
EOFError: Ran out of input

**Comment by JiaxuanYou** [comment]
Hi, based on the error log, it seems that something wrong is happening with your PyTorch Geometric data loader when loading `Planetoid` dataset. The error is not generated from GraphGym.
You can try to remove the cached files of `Planetoid` dataset.
You can check your installation of PyTorch Geometric to see if it is the latest version.

Hope it helps. I will mark this issue as resolved for now, and feel free to reopen it if needed.
