### ISSUE TITLE
Crash at end of regression runs

### ISSUE THREAD

**Issue by mszulcz-mitre** [snap-stanford/GraphGym#57]
When I make a run with `cfg.dataset.task_type = 'regression'`, the code crashes at the end of the run.  The error message is:
 ```
Traceback (most recent call last):
  File "main_pyg.py", line 55, in <module>
    agg_runs(cfg.out_dir, cfg.metric_best)
  File "~/Code/GraphGym/graphgym/utils/agg_runs.py", line 100, in agg_runs
    [stats[metric] for stats in stats_list])
  File "~/Code/GraphGym/graphgym/utils/agg_runs.py", line 100, in <listcomp>
    [stats[metric] for stats in stats_list])
KeyError: 'accuracy'
```
The problem seems to be that `accuracy` is not a metric logged for regression tasks.  Here are the relevant lines in `agg_runs.py`:
``` python
                if metric_best == 'auto':
                    metric = 'auc' if 'auc' in stats_list[0] else 'accuracy'
```
Here's a fix:
``` python
                if metric_best == 'auto':
                    if cfg.dataset.task_type == 'classification':
                        metric = 'auc' if 'auc' in stats_list[0] else 'accuracy'
                    elif cfg.dataset.task_type == 'regression':
                        metric = 'mse'
```

**Comment by gogowinner** [comment]
You may also need to add cfg.metric_agg = 'argmin' to get accurate results.

**Comment by gogowinner** [comment]
In order to perform the regression, it will also be necessary to add metric_agg: argmin inside the yaml file in order to get the desired results with MSE.
